name: Publish synthetmic to PyPI

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build-n-publish:
    name: Build and publish synthetmic to PyPI
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.15"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ">=3.11" # "pyproject.toml" # ".python-version"
        architecture: 'x64'

    - name: Install the project
      run: uv sync --all-extras

    - name: Run tests
      run: uv run pytest -v tests

    - name: Build package
      run: uv build

    - name: Publish synthetmic to PyPI
      run: uv publish
